### PR TITLE
avoid the speech recognition part of a chatrobot hearing the content spoken from chatrobot

### PR DESCRIPTION
**Pull request by QGSQ**
Suppose that we want to creat a chatrobot consisting of three parts. They are Speech Recognition (vosk), NLP (Chatgpt) and Text-to-Speech (tams_tts). We don't want that Speech Recognition part hears the content spoken by Text-to-Speech part. We only want that Speech Recognition part hears what human says. 

We avoid that case by publishing a ros topic Robot_is_speaking from Text-to-Speech part. If chatrobot is speeking, then Speech Recognition part will stop hearing by subscribing this topic (Robot_is_speaking). This topic acts like a trigger.

### CODE REVIEW

**Comment by normanhendrich** [comment]
Well, having the topic is useful. (Typically, topic names are lowercase, though). 

The implementation using sleep() is not optimal, and might complicate upper-level code. For example, we could not easily run another tts command for the next sentence(s) when we sleep while the robot is speaking the current sentence.

The real complication is on the listener side. If we just stop listening while the robot speaks, we will miss user commands spoken during this time. For example, the user could not "stop" or interrupt the robot at all, when the robot was speaking continuously. At least the robot should wait to speak until no user-voice is detected...

**Comment by QGSQ** [comment]
> Well, having the topic is useful. (Typically, topic names are lowercase, though).
> 
> The implementation using sleep() is not optimal, and might complicate upper-level code. For example, we could not easily run another tts command for the next sentence(s) when we sleep while the robot is speaking the current sentence.
> 
> The real complication is on the listener side. If we just stop listening while the robot speaks, we will miss user commands spoken during this time. For example, the user could not "stop" or interrupt the robot at all, when the robot was speaking continuously. At least the robot should wait to speak until no user-voice is detected...

Thank you for your comment. You list some practical cases.

I would like to change the topic name in lowercase-letters.

The generation of speech and making sound from speaker are two separat steps. We could truncate a long text from Chatgpt in several sentences and generate several small speech from those sentences. the sleep() function will not disturb this generation process, it is just used for changing the status of "robot_is_speaking" from True to False according to length of speech, in order that the speech recognition part does not listen during the time.

Now I just consider that Robot and Human communicate with each other in a polite way. :) That is to say, Human will not stop or interrupt the robot, when it is speaking. Maybe later we could implement the function that human can interrupt the robot, then the robot make new response to the human's request and just discard the content of last response which is not finished to spoken out.

**Comment by v4hn** [comment]
Thanks for the patch @QGSQ . I cleaned up the patch and reworked it to use a rospy.Timer over sleep, to allow new statements to be processed while the system is talking and to repair the "demo" mode which slept twice with your patch.

**Comment by QGSQ** [comment]
Hi Michael, There is an issue with the use of the "Timer" here. 

Assuming that there are several texts in the queue of the "say" topic, in the speak() function, they will be sequentially converted into speech and sent to the "audio" topic. Here, after the conversion of each text to speech is completed, the previous Timer is shut down and a new Timer is triggered. 

As the "audio_play" process is slow, it may happen that the audio output is not finished, and the Timer's duration runs out, causing "is_speaking" topic to be set to False. This will result in the speech recognition system hearing the robot's voice, which cannot be avoided.

**Comment by v4hn** [comment]
Please have a look at the current state of the repository. I added a separate internal queue for the generated audio in order to process multi-sentence inputs per sentence as well. This should resolve the issue.

**Pull request merged**
